
# All possible values that should be constant through the entire script

ERR_CODE_NON_EXISTING_FILE = 404
ERR_CODE_CREATING_XML = 406
ERR_CODE_COMMAND_LINE_ARGS = 407
ERR_CODE_NON_EXISTING_DIRECTORY = 408
ERR_CODE_NON_EXISTING_W_E = 409

WARNING_CODE_INVALID_FORMAT = 405
WARNING_CODE_NO_PAIR_FOUND = 406
WARNING_NOT_A_TMX_FILE = 407

COMMAND_LINE_MIN_ARGS = 2
COMMAND_LINE_COMMAND_NAME_POSITION = 1

COMMAND_NAME_HELP = '-help'
COMMAND_NAME_CREATE_TMX = '-mktmx'
COMMAND_NAME_CREATE_VTT = '-mkvtt'
COMMAND_NAME_DEV = "-dev"

TMX_MIN_ARGS = [4, 2]
VTT_MIN_ARGS = [2]

WINDOW_GENERATE_TMX = 1
WINDOW_GENERATE_VTT = 2
WINDOW_ABOUT = 3

SUPPRESS_CONSOLE_PRINT = True
PRINT_MESSAGEBOX = 1
PRINT_CONSOLE = 2

WINDOW_WIDTH = 300
WINDOW_HEIGHT = 280

GRID_CONFIGURATIONS = {
    'padx': 12,
    'pady': 8
}
